force-app/main/default/objects/Program_Assignment__c/Program_Assignment__c.object-meta.xml
<CustomObject>
    <label>Program Assignment</label>
    <nameField>
        <label>Program Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Assignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Assignments</relationshipLabel>
    <relationshipName>Program_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProgramManagementClass.cls
public with sharing class ProgramManagementClass {
    
    @AuraEnabled(cacheable=true)
    public static List<Program_Assignment__c> getAllProgramAssignmentsRelatedToContact(String contactId){
        try {
            return [
                SELECT Id,Name 
                FROM Program_Assignment__c
                WHERE Contact__c = :contactId
            ];
        }
        catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void insertServiceDelivery(List<Service_Delivery__c> serviceDeliveryList){
        try {
            insert serviceDeliveryList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

}