force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Assignment__c/Program_Assignment__c.object-meta.xml
<CustomObject>
    <label>Program Assignment</label>
    <nameField>
        <label>Program Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Assignment__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Assignments</relationshipLabel>
    <relationshipName>Program_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProgramTriggerHandler.cls
public with sharing class ProgramTriggerHandler extends TriggerHandler{
    
    public override virtual void afterUpdate() {
        Map<Id,Program__c> newPrograms = (Map<Id,Program__c>) Trigger.newMap;
        Map<Id,Program__c> oldPrograms = (Map<Id,Program__c>) Trigger.oldMap;

        Set<Id> programsIds = new Set<Id> ();

        for(Id programId : newPrograms.keySet()){
            Program__c newProgram = newPrograms.get(programId);
            Program__c oldProgram = oldPrograms.get(programId);

            if(newProgram.Name != oldProgram.Name){
                programsIds.add(programId);
            }
        }

        List<Program_Assignment__c> programAssignments = SOQLQueryHelper.programAssignmentsWithAutonameTrue(programsIds);

        for(Program_Assignment__c pA : programAssignments){
            pA.Name = 'Changed'; // This will call beforeUpdate trigger in ProgramAssignmentTriggerHandler and change related ProgramAssigns.  
        }

        update programAssignments;
    }

    public override virtual void beforeDelete(){
        ProgramTriggerHelper.deleteExeptionIfChildNotAvailableForDelete((Map<Id,Program__c>) Trigger.oldMap);
        ProgramTriggerHelper.deleteProgramAssignmentRelatedToDeletedProgram((Map<Id,Program__c>) Trigger.oldMap);
    }
}