force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Assignment__c/Program_Assignment__c.object-meta.xml
<CustomObject>
    <label>Program Assignment</label>
    <nameField>
        <label>Program Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Assignment__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Assignments</relationshipLabel>
    <relationshipName>Program_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProgramTriggerHandlerTest.cls
@isTest
public class ProgramTriggerHandlerTest {
    

    @isTest
    static void TestProgramTriggerAfterUpdate(){
        Program__c program = TestDataFactory.createProgram();
        List<Program_Assignment__c> programAssignments = TestDataFactory.createProgramAssignment(program,2);

        Test.startTest();

        Program__c updatedProgram1 = [SELECT Id, Name FROM Program__c WHERE Id =:program.Id LIMIT 1];
        updatedProgram1.Name = 'new Test 1';
        update updatedProgram1;

        Test.stopTest();
        
        List<Program_Assignment__c> updatedAssignments = [
            SELECT Name, Program__c 
            FROM Program_Assignment__c 
            WHERE Program__c =:updatedProgram1.Id
        ];
        for (Program_Assignment__c pA : updatedAssignments) {
            System.assertEquals('Help Contact new Test 1 : null', pA.Name, 'Program Assignment name was not updated correctly.');
        }
    }


    @isTest
    static void TestBeforeDeleteDelRelatedProgramAssignments() {
        Program__c program = TestDataFactory.createProgram();
        List<Program_Assignment__c> programAssignments = TestDataFactory.createProgramAssignment(program, 2);

        Test.startTest();
        
        delete program;

        Test.stopTest();
        List<Program_Assignment__c> relatedAssignments = [
            SELECT Name, Program__c 
            FROM Program_Assignment__c 
            WHERE Program__c =:program.Id
        ];

        System.assertEquals(0, relatedAssignments.size(), 'Program Assignments were not deleted.');
    }

    @isTest
    static void TestBeforeDeleteExeptionIfChildNotAvailableForDelete() {
        Program__c program = TestDataFactory.createProgram();
        Program_Assignment__c programAssignment = TestDataFactory.createProgramAssing(program);

        Test.startTest();
            try {
                delete program;
                System.assert(false, 'Expected an error to be thrown when deleting a program with an applied assignment');
            } catch (DmlException e) {
                System.assert(e.getMessage().contains('Nope'), 'Error message not as expected: ' + e.getMessage());
            }
        Test.stopTest();
    }
}