force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Assignment__c/Program_Assignment__c.object-meta.xml
<CustomObject>
    <label>Program Assignment</label>
    <nameField>
        <label>Program Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Assignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Assignments</relationshipLabel>
    <relationshipName>Program_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Assignments</relationshipLabel>
    <relationshipName>Program_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProgramAssignmentTriggerHandlerTest.cls
@isTest
public with sharing class ProgramAssignmentTriggerHandlerTest {
    
    @isTest
    private static void beforeInsertTest(){
        Program__c program = TestDataFactory.createProgram();
        Contact contact = new Contact(LastName = 'Test' , FirstName = 'Test Contact');
        insert contact;
        Program_Assignment__c programAssignment = TestDataFactory.createProgramAssignmentWithEnteredContactAndProgram(program,contact);

        Test.startTest();
        
            insert programAssignment;
        
        Test.stopTest();

        Program_Assignment__c programAssignmentAfterInsert = [
            SELECT Id,Name 
            FROM Program_Assignment__c
            WHERE Id =:programAssignment.Id
            LIMIT 1
            ];
        Assert.areEqual('Test Contact - Test : 20.12.2024', programAssignmentAfterInsert.Name,'name was not generated');
    }

    @isTest
    private static void beforeUpdateTest(){
        Program__c program = TestDataFactory.createProgram();
        
        Contact contact = new Contact(LastName = 'Test' , FirstName = 'Test Contact');
        insert contact;
        
        Program_Assignment__c programAssignment = TestDataFactory.createProgramAssignmentWithEnteredContactAndProgram(program,contact);
        insert programAssignment;
        
        Contact contactNew = new Contact(LastName = 'QA' , FirstName = 'QA');
        insert contactNew;
        
        programAssignment.Contact__c = contactNew.Id;

        Test.startTest();
        
        update programAssignment;
        
        Test.stopTest();

        Program_Assignment__c programAssignmentAfterInsert = [
            SELECT Id,Name 
            FROM Program_Assignment__c
            WHERE Id =:programAssignment.Id
            LIMIT 1
            ];
        Assert.areEqual('QA - Test : 20.12.2024', programAssignmentAfterInsert.Name,'name was not generated');
    }

}