force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Assignment__c/Program_Assignment__c.object-meta.xml
<CustomObject>
    <label>Program Assignment</label>
    <nameField>
        <label>Program Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Assignment__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Assignments</relationshipLabel>
    <relationshipName>Program_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProgramAssignmentHelper.cls
public with sharing class ProgramAssignmentHelper {
    
    public static Program_Assignment__c generateNameAndAddToObject(Program_Assignment__c pA,Contact contact, Program__c program){
        if(contact != null && program != null){
            if(contact.Name != null && program.Name != null && pA.Start_Date__c != null){
                pA.Name = contact.Name + ' - ' + program.Name + ' : ' +  pA.Start_Date__c.format();
            }
            else {
                pA.Name = 'Mykhailo Mudryk ';  
            }
            return pA;
        }
        return pA;
    }
}