force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Assignment__c/Program_Assignment__c.object-meta.xml
<CustomObject>
    <label>Program Assignment</label>
    <nameField>
        <label>Program Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Assignment__c/fields/Autoname__c.field-meta.xml
<CustomField>
    <fullName>Autoname__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Apex trigger will generate name for Program Assignment record if this checkbox is true</description>
    <label>Autoname</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Assignments</relationshipLabel>
    <relationshipName>Program_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Assignments</relationshipLabel>
    <relationshipName>Program_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProgramAssignmentTriggerHandler.cls
public with sharing class ProgramAssignmentTriggerHandler extends TriggerHandler {
    
    public override void beforeInsert() {
        List<Program_Assignment__c> programAssignmentList = Trigger.New;
        Set<Id> contactIds = new Set<Id>();
        Set<Id> protgramsIds = new Set<Id>();

        for (Program_Assignment__c pA : programAssignmentList) {
            if(pA.Autoname__c){
                contactIds.add(pA.Contact__c);
                protgramsIds.add(pA.Program__c);
            }
        }

        Map<Id,Contact> contacts = new Map<Id,Contact>(SOQLQueryHelper.getContactsByIdsSet(contactIds));
        Map<Id,Program__c> programs = new Map<Id,Program__c> (SOQLQueryHelper.getProgramsByIdSet(protgramsIds));

        for(Program_Assignment__c pA : programAssignmentList){
            ProgramAssignmentHalper.generateNameAndAddToObject(
                pA,contacts.get(pA.Contact__c),programs.get(pA.Program__c));
        }
    }

    public override void beforeUpdate() { 
        List<Program_Assignment__c> programAssignmentList = Trigger.New;
        Map<Id,Program_Assignment__c> programAssignmentOldMap = (Map<Id,Program_Assignment__c>) Trigger.oldMap;
        Set<Id> contactIds = new Set<Id>();
        Set<Id> protgramsIds = new Set<Id>();
        
        Boolean autoNameIsElected = false;
        for (Program_Assignment__c pA : programAssignmentList) {
                if(pA.Autoname__c && pA.Autoname__c != programAssignmentOldMap.get(pA.Id).Autoname__c){
                        autoNameIsElected = true;
                        contactIds.add(pA.Contact__c);
                    }
                if(pA.Autoname__c && pA.Contact__c != programAssignmentOldMap.get(pA.Id).Contact__c){
                    autoNameIsElected = true;
                    contactIds.add(pA.Contact__c);
                    protgramsIds.add(pA.Program__c);
                }
                if(pA.Autoname__c && pA.Program__c != programAssignmentOldMap.get(pA.Id).Program__c){
                    autoNameIsElected = true;
                    contactIds.add(pA.Contact__c);
                    protgramsIds.add(pA.Program__c);
                }
                if(pA.Autoname__c && pA.Start_Date__c != programAssignmentOldMap.get(pA.Id).Start_Date__c){
                    autoNameIsElected = true;
                    contactIds.add(pA.Contact__c);
                    protgramsIds.add(pA.Program__c);
                }
                if(pA.Autoname__c && pA.Name != programAssignmentOldMap.get(pA.Id).Name){
                    autoNameIsElected = true;
                    contactIds.add(pA.Contact__c);
                    protgramsIds.add(pA.Program__c);
                }
            }
            
        if(autoNameIsElected){
            Map<Id,Contact> contacts = new Map<Id,Contact>(SOQLQueryHelper.getContactsByIdsSet(contactIds));
            Map<Id,Program__c> programs = new Map<Id,Program__c> (SOQLQueryHelper.getProgramsByIdSet(protgramsIds));

            for(Program_Assignment__c pA : programAssignmentList){
                ProgramAssignmentHalper.generateNameAndAddToObject(
                pA,contacts.get(pA.Contact__c),programs.get(pA.Program__c));
            }
        }
    }
}