force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Assignment__c/Program_Assignment__c.object-meta.xml
<CustomObject>
    <label>Program Assignment</label>
    <nameField>
        <label>Program Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Assignment__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Assignments</relationshipLabel>
    <relationshipName>Program_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProgramTriggerHelper.cls
public with sharing class ProgramTriggerHelper {
    
    public static void deleteProgramAssignmentRelatedToDeletedProgram(Map<Id, Program__c> deletedRecordsMap){
        Set<Id> programIds = deletedRecordsMap.keySet();
        List<Program_Assignment__c> programAssignments = SOQLQueryHelper.programAssignmentsWithoutProgram(programIds);
        if(programAssignments.size() == 0){
            System.debug(' programAssignments is empty');
        }
        delete programAssignments;
    }

    public static void deleteExeptionIfChildNotAvailableForDelete(Map<Id, Program__c> deletedRecordsMap) {
        Set<Id> programIds = new Set<Id>();
        List<Program_Assignment__c> programAssignments = SOQLQueryHelper.programAssignmentsWithStatusDeniedOrApplied();

        for(Program_Assignment__c pA : programAssignments){
            programIds.add(pA.Program__c);
        }

        for(Program__c pg : deletedRecordsMap.values()){
            if(programIds.contains(pg.Id)){ 
                pg.addError('Nope');
            }
        }
    }
}