force-app/main/default/objects/Lead/fields/Outreaches_count__c.field-meta.xml
<CustomField>
    <fullName>Outreaches_count__c</fullName>
    <label>Outreaches count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Successful_Outreaches__c.field-meta.xml
<CustomField>
    <fullName>Successful_Outreaches__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Successful Outreaches</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Outreach__c/Outreach__c.object-meta.xml
<CustomObject>
    <label>Outreach</label>
    <nameField>
        <displayFormat>ON-{0000}</displayFormat>
        <label>Outreach Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outreachs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Outreach__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Outreachs</relationshipLabel>
    <relationshipName>Outreachs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Outreach__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <description>Outcome of Outreach work</description>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Responded</fullName>
                <default>true</default>
                <label>Not Responded</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OutreachTriggerHandlerTest.cls
@isTest
public with sharing class OutreachTriggerHandlerTest {

    @TestSetup
    static void makeData(){
        Lead lead = TestDataFactory.generateLead();
        insert lead;
        List<Outreach__c> outreaches = TestDataFactory.generateOutreaches(lead,3);
        insert outreaches;
    }
    
    @isTest
    private static void afterInserOutreachtSuccessfulTest(){
        Lead oldLead = [SELECT Id,Name,Outreaches_count__c,Successful_Outreaches__c FROM Lead WHERE Name  = 'Test Lead' LIMIT 1];
        List<Outreach__c> outreaches = TestDataFactory.generateOutreaches(oldLead,3);

        Test.startTest();
            insert outreaches;
        Test.stopTest();

        Lead lead = [SELECT Id,Name,Outreaches_count__c,Successful_Outreaches__c FROM Lead WHERE Name  = 'Test Lead' LIMIT 1];
        System.Assert.areEqual(6,lead.Outreaches_count__c, 'The number of outreaches should be 3');
    }

    @isTest
    private static void afterUpdateOutreachSuccessfulTest(){
        Lead oldLead = [SELECT Id,Name,Outreaches_count__c,Successful_Outreaches__c FROM Lead WHERE Name  = 'Test Lead' LIMIT 1];
        List<Outreach__c> outreaches = [SELECT Id,Name,Lead__c,Outcome__c FROM Outreach__c WHERE Lead__c =:oldLead.Id];

        for(Outreach__c outreach : outreaches){
            outreach.Outcome__c = 'Accepted';
        }
        Test.startTest();
            update outreaches;
        Test.stopTest();

        Lead lead = [SELECT Id,Name,Outreaches_count__c,Successful_Outreaches__c FROM Lead WHERE Name  = 'Test Lead' LIMIT 1];
        System.Assert.areEqual(3,lead.Successful_Outreaches__c, 'The number of successful outreaches should be 3');
    }

    @isTest
    private static void afterDeleteOutreachSuccessfulTest(){
        Lead oldLead = [SELECT Id,Name,Outreaches_count__c,Successful_Outreaches__c FROM Lead WHERE Name  = 'Test Lead' LIMIT 1];
        List<Outreach__c> outreaches = [SELECT Id,Name,Lead__c,Outcome__c FROM Outreach__c WHERE Lead__c =:oldLead.Id];

        Test.startTest();
            delete outreaches;
        Test.stopTest();

        Lead lead = [SELECT Id,Name,Outreaches_count__c,Successful_Outreaches__c FROM Lead WHERE Name  = 'Test Lead' LIMIT 1];
        System.Assert.areEqual(0,lead.Outreaches_count__c, 'The number of outreaches should be 0');
    }

    @isTest
    private static void afterUndeleteOutreachSuccessfulTest(){
        Lead oldLead = [SELECT Id,Name,Outreaches_count__c,Successful_Outreaches__c FROM Lead WHERE Name  = 'Test Lead' LIMIT 1];
        List<Outreach__c> outreaches = [SELECT Id,Name,Lead__c,Outcome__c FROM Outreach__c WHERE Lead__c =:oldLead.Id];

        for(Outreach__c outreach : outreaches){
            outreach.Outcome__c = 'Accepted';
        }
        
        delete outreaches;

        Test.startTest();
            undelete outreaches;
        Test.stopTest();

        Lead lead = [SELECT Id,Name,Outreaches_count__c,Successful_Outreaches__c FROM Lead WHERE Name  = 'Test Lead' LIMIT 1];
        System.Assert.areEqual(3,lead.Outreaches_count__c, 'The number of successful outreaches should be 3');
    }
}