force-app/main/default/objects/Lead/fields/Outreaches_count__c.field-meta.xml
<CustomField>
    <fullName>Outreaches_count__c</fullName>
    <label>Outreaches count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Successful_Outreaches__c.field-meta.xml
<CustomField>
    <fullName>Successful_Outreaches__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Successful Outreaches</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Outreach__c/Outreach__c.object-meta.xml
<CustomObject>
    <label>Outreach</label>
    <nameField>
        <displayFormat>ON-{0000}</displayFormat>
        <label>Outreach Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outreachs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Outreach__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Outreachs</relationshipLabel>
    <relationshipName>Outreachs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Outreach__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <description>Outcome of Outreach work</description>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Responded</fullName>
                <default>true</default>
                <label>Not Responded</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OutreachTriggerHelper.cls
public with sharing class OutreachTriggerHelper {

    public static void updateLeadCountOutreachField(){

        Boolean leadFieldIsChanged = false;
        
        List<Lead> leadsList = SOQLQueryHelper.getAllLeadsAndFewParamFromOutreach();
        
        for(Lead lead : leadsList){

            Integer countOfChild = 0;
            Integer countOfAcceptedChild = 0;

            for(Outreach__c outreach : lead.Outreachs__r){
                countOfChild++;
                if(outreach.Outcome__c == 'Accepted'){
                    countOfAcceptedChild++;
                }
            }

            lead.Outreaches_count__c = countOfChild;
            lead.Successful_Outreaches__c = countOfAcceptedChild;
        }

        update leadsList;
    }


    public static void updateLeadCountOutreachFieldAfterChanges(Map<Id,Outreach__c> newOutreaches,Map<Id,Outreach__c> oldOutreaches){

        Boolean leadOrOutcomeFieldsAreChanged = false;

        for(Outreach__c newOutreach : newOutreaches.values()){
            if(newOutreach.Lead__c != oldOutreaches.get(newOutreach.Id).Lead__c){
                leadOrOutcomeFieldsAreChanged = true;
            }
            else if(newOutreach.Outcome__c != oldOutreaches.get(newOutreach.Id).Outcome__c){
                leadOrOutcomeFieldsAreChanged = true;
            }

        }
        if(leadOrOutcomeFieldsAreChanged){
            List<Lead> leadsList = SOQLQueryHelper.getAllLeadsAndFewParamFromOutreach();
            
            for(Lead lead : leadsList){

                Integer countOfChild = 0;
                Integer countOfAcceptedChild = 0;

                for(Outreach__c outreach : lead.Outreachs__r){
                    countOfChild++;
                    if(outreach.Outcome__c == 'Accepted'){
                        countOfAcceptedChild++;
                    }
                }

                lead.Outreaches_count__c = countOfChild;
                lead.Successful_Outreaches__c = countOfAcceptedChild;
            }

            update leadsList;
        }
    }
}