force-app/main/default/objects/Contact/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <label>Outcome</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Successful_Outreaches__c.field-meta.xml
<CustomField>
    <fullName>Successful_Outreaches__c</fullName>
    <label>Successful Outreaches</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Outreaches_count__c.field-meta.xml
<CustomField>
    <fullName>Outreaches_count__c</fullName>
    <label>Outreaches count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Successful_Outreaches__c.field-meta.xml
<CustomField>
    <fullName>Successful_Outreaches__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Successful Outreaches</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Outreach__c/Outreach__c.object-meta.xml
<CustomObject>
    <label>Outreach</label>
    <nameField>
        <displayFormat>ON-{0000}</displayFormat>
        <label>Outreach Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outreachs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Outreach__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Outreachs</relationshipLabel>
    <relationshipName>Outreachs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Outreach__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <description>Outcome of Outreach work</description>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Responded</fullName>
                <default>true</default>
                <label>Not Responded</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/Program_Assignment__c.object-meta.xml
<CustomObject>
    <label>Program Assignment</label>
    <nameField>
        <label>Program Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Assignment__c/fields/Autoname__c.field-meta.xml
<CustomField>
    <fullName>Autoname__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Apex trigger will generate name for Program Assignment record if this checkbox is true</description>
    <label>Autoname</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Assignments</relationshipLabel>
    <relationshipName>Program_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
                <default>true</default>
                <label>Applied</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SOQLQueryHelper.cls
public inherited sharing class SOQLQueryHelper {

    public static List<Contact> getContactsByIdsSet(Set<Id> contactIds){
        return [SELECT Id,FirstName FROM Contact WHERE Id IN :contactIds];
    }

    public static List<Program__c> getProgramsByIdSet(Set<Id> programIds){
        return [SELECT Id, Name FROM Program__c WHERE Id IN :programIds];
    }

    public static List<Program_Assignment__c> programAssignmentsWithAutonameTrue(Set<Id> programsIds){
        return [
            SELECT Name,Id FROM Program_Assignment__c 
            WHERE Program__c IN :programsIds AND Autoname__c = true
        ];
    }

    public static List<Program_Assignment__c> programAssignmentsWithAnyStatusExceptDeniedOrApplied(){
        return [
            SELECT Id, Program__c 
            FROM Program_Assignment__c 
            WHERE Status__c NOT IN ('Denied' ,'Applied')
        ];
    }

    public static List<Program_Assignment__c> programAssignmentsWithoutProgram(Set<Id> programsIds){
        return [
            SELECT Id FROM Program_Assignment__c 
            WHERE Program__c IN :programsIds 
        ];
    }

    public static List<Lead> getAllLeadsAndFewParamFromOutreach(){
        List<Lead> leadsList = new List<Lead> ([
            SELECT Id,Name,Outreaches_count__c,Successful_Outreaches__c,(SELECT Name,Outcome__c FROM Outreachs__r) 
            FROM Lead
            ]);
            return leadsList;
    }
}