force-app/main/default/objects/Contact/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <label>Outcome</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Need_Attention__c.field-meta.xml
<CustomField>
    <fullName>Need_Attention__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Need Attention</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Outreach__c/Outreach__c.object-meta.xml
<CustomObject>
    <label>Outreach</label>
    <nameField>
        <displayFormat>ON-{0000}</displayFormat>
        <label>Outreach Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outreachs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Outreach__c/fields/Communication_Method__c.field-meta.xml
<CustomField>
    <fullName>Communication_Method__c</fullName>
    <label>Communication Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Outreach__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Outreachs</relationshipLabel>
    <relationshipName>Outreachs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Outreach__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <description>Outcome of Outreach work</description>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Responded</fullName>
                <default>true</default>
                <label>Not Responded</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Skill_Program</fullName>
                <label>Skill Program</label>
            </value>
            <value>
                <fullName>Help_Program</fullName>
                <label>Help Program</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/Program_Assignment__c.object-meta.xml
<CustomObject>
    <label>Program Assignment</label>
    <nameField>
        <label>Program Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Assignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Assignments</relationshipLabel>
    <relationshipName>Program_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Assignments</relationshipLabel>
    <relationshipName>Program_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
                <default>true</default>
                <label>Applied</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {


    public static Program__c createProgram(String Name,String Type){
        Program__c program = new Program__c(Name = Name,Type__c = Type);
        insert program;
        return program;
    }

    public static List<Program_Assignment__c> createProgramAssignment(Program__c program, Integer numProgAssPerProgram) {
        List<Program_Assignment__c> programAssignments = new List<Program_Assignment__c>();
        
        Contact contact = new Contact(LastName = 'Test Contact');
        insert contact;

        for (Integer j = 0; j < numProgAssPerProgram; j++) {
            Program_Assignment__c newProgramAssign = new Program_Assignment__c(
                Name = '', 
                Program__c = program.Id, 
                Contact__c = contact.Id
            );
            programAssignments.add(newProgramAssign);
        }
        
        insert programAssignments;
        
        return programAssignments;
    }

    public static Contact createContactByFirstAndLastName(String firstName, String LastName){
        Contact contact = new Contact(FirstName = firstName,LastName = LastName);
        insert contact;
        return contact;
    }

    public static Program_Assignment__c createProgramAssing(Program__c program) {
        Contact contact = new Contact(LastName = 'Test Contact');
        insert contact;
        Program_Assignment__c newProgramAssign = new Program_Assignment__c(
            Name = '', 
            Program__c = program.Id, 
            Contact__c = contact.Id,
            Status__c = 'Completed'
        );
        
        insert newProgramAssign;
        
        return newProgramAssign;
    }

    public static Lead generateLead(){
        Lead lead = new Lead(
            LastName = 'Test Lead',
            Company = 'Test Company',
            Need_Attention__c = false,
            OwnerId = UserInfo.getUserId()
        );
        return lead;
    }

    public static Outreach__c generateOutreach(Lead lead){
        Outreach__c outreach = new Outreach__c(
            Lead__c = lead.Id,
            Outcome__c = 'Declined',
            Communication_Method__c = 'Phone'
        );
        return outreach;
    }

    public static List<Outreach__c> generateOutreaches(Lead lead,Integer quantity){
        List<Outreach__c> outreaches = new List<Outreach__c>();
        for(Integer i=0; i<quantity; i++){
            outreaches.add(generateOutreach(lead));
        }
        return outreaches;
    }


    public static Program_Assignment__c createProgramAssignmentWithEnteredContactAndProgram(Program__c program,Contact contact){
        Program_Assignment__c newProgramAssign = new Program_Assignment__c(
            Name = '', 
            Program__c = program.Id, 
            Contact__c = contact.Id,
            Start_Date__c = Date.newInstance(2024, 12, 20)
        );

        return newProgramAssign;
    }
    
    public static Program_Assignment__c createProgramAssignmentWithEnteredContactAndProgramAndInsert(Program__c program,Contact contact){
        Program_Assignment__c newProgramAssign = new Program_Assignment__c(
            Name = '', 
            Program__c = program.Id, 
            Contact__c = contact.Id,
            Start_Date__c = Date.newInstance(2024, 12, 20)
        );
        insert newProgramAssign;
        return newProgramAssign;
    }
}